<?php

namespace NDM\Bundle\TryCatch\ApiBundle\Entity;


/**
 * ComponentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\Query;

use Doctrine\ORM\Query\Expr;

class ComponentRepository extends EntityRepository
{

	public function findAsArray($types = array()) {
		$qb = $this->createQueryBuilder('c');
        $qb
            ->select('c', 'ch', 'chan', 'rel')
            ->leftJoin('c.channels', 'ch')
            ->leftJoin('ch.channel', 'chan')
            ->leftJoin('c.releases', 'rel')
        ;

        if(is_array($types) && count($types) > 0) {
            $qb->andWhere($qb->expr()->in('c.name', ':types'))
                ->setParameter('types', $types);
        }

        return $qb->getQuery()->execute(array(), Query::HYDRATE_ARRAY);
	}
}
