<?php

namespace NDM\TryCatchBundle\Entity;


/**
 * ComponentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\Query;

use Doctrine\ORM\Query\Expr;

class ComponentRepository extends EntityRepository
{

	public function findAllAsArray() {
		return $this->createQueryBuilder('c')->select('c', 'ch', 'chan')->innerJoin('c.channels', 'ch')->innerJoin('ch.channel', 'chan')->getQuery()->execute(array(), Query::HYDRATE_ARRAY);
	}
}